### ISSUE TITLE
Bitwig 2.0 support?

### ISSUE THREAD

**Issue by adamjmurray** [ThomasHelzle/Toms_Bitwig_Scripts#3]
Hi Tom,
Have you tried your scripts with Bitwig 2.0? I can't get them to work anymore since upgrading. Tracks using "Tom's MIDI controllers" aren't receiving any MIDI input in Bitwig 2.0.

**Comment by ThomasHelzle** [comment]
The separation of midi channels is broken in the 2.0 API, only "Omni" works, nothing I can do about it. :-(
The team is aware of it, but I don't know what the plans are for this area.
I would highly prefer a native solution to my workaround in the scripts, since it makes the input-dropdown so large. There are new midi channel devices in 2.1 beta but I didn't have the time to test them yet.
Sorry.

**Comment by adamjmurray** [comment]
Ok, no problem. Thanks for the quick response.

I agree. We should have a native solution to this. I will pester Bitwig about it. 

I'm actually beta testing 2.1, but the features I thought would replace your scripts aren't quite working yet. Hopefully this will all be sorted out soon.

**Comment by ThomasHelzle** [comment]
Hey adam, does it work for you in BWS 2.1 Beta 2 now?

-

**Comment by adamjmurray** [comment]
Yes! It's working with that version again.

**Comment by ThomasHelzle** [comment]
Great! :-)
